# Generated by Django 5.1.6 on 2025-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_all_description_task_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('Лёгкий', 'Easy'), ('Средний', 'Middle'), ('Сложный', 'Different')], default='Easy', max_length=8),
        ),
    ]
