# Generated by Django 5.1.6 on 2025-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('Лёгкий', 'Easy'), ('Средний', 'Middle'), ('Сложный', 'Different')], default='Лёгкий', max_length=8),
        ),
    ]
