# Generated by Django 5.1.6 on 2025-02-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='all_description',
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Образец', unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('Easy', 'Лёгкий'), ('Middle', 'Средний'), ('Diff', 'Сложный')], default='Easy', max_length=6),
        ),
    ]
